services:
  mysql:
    image: mysql:8.0.33
    container_name: conference-mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=conference-db
